server:
  port: 3000  # 3000 ? ?? ??

spring:
  datasource:
    # DB URL
    url: jdbc:mysql://footprint.cyk6hh5fzxrl.us-east-2.rds.amazonaws.com/footprintdb

    # DB Username
    username: admin # ?? ?? ???? ????? ???? admin ???

    # DB Password
    password: umcfootprint # ????? ??????!

    # DB Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql