server:
  port: 3000  # 3000? ??? ??

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://footprint.cyk6hh5fzxrl.us-east-2.rds.amazonaws.com/footprintdb
  # url ??? jdbc:mysql://RDS? EndPoint/?? DB ???? ???.
    username: admin # ?? ?? ???? ????? ???? admin ???
    password: umcfootprint # ????? ??????!
    driver-class-name: com.mysql.cj.jdbc.Driver