server:
  port: 3000  # 3000 ? ?? ??

#spring:
#  datasource:
#    # DB URL
#    url: jdbc:mysql://footprint.cyk6hh5fzxrl.us-east-2.rds.amazonaws.com/footprintdb
#
#    # DB Username
#    username: admin # ?? ?? ???? ????? ???? admin ???
#
#    # DB Password
#    password: umcfootprint # ????? ??????!
#
#    # DB Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devfootprint
    username: root
    password: seung0507*
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 275484626544-npc9k2gt2qmh36o90slhb73bmdgatrnk.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email