name: footprint-springboot-gradle-ci

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Copy Yaml File
      run: cp ./Security-Server/*.yml ./footprint/src/main/resources/
      
    - name: Rename Yaml File
      run: |
        mv ./footprint/src/main/resources/applicationDev.yml ./footprint/src/main/resources/application.yml
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./footprint/gradlew
        
    - name: Build with Gradle
      working-directory: ./footprint
      run: ./gradlew build
      
    - name: Publish Unit Test Results # test 후 result를 보기 위해 추가
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
      with:
        files: build/test-results/**/*.xml
