name: footprint-master-springboot-gradle-docker-ec2-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Copy Yaml File
      run: cp ./Security-Server/*.yml ./footprint/src/main/resources/
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./footprint/gradlew
        
    - name: Build with Gradle
      working-directory: ./footprint
      run: ./gradlew build
      
    - name: Build Docker Image
      working-directory: ./footprint
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/footprint_master .
    
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Hub Publish
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/footprint_master
      

    - name: EC2 Docker Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          docker stop footprint_master
          docker rm footprint_master
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/footprint_master
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/footprint_master
          nohup docker run -p ${{ secrets.PROD_PORT }}:${{ secrets.PROD_PORT }} --name footprint_master ${{ secrets.DOCKERHUB_USERNAME }}/footprint > prod_server.log 2>&1 &
